controller_manager:
  ros_parameters:
    update_rate: 50

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    diff_drive_controller:
      type: diff_drive_controller/DiffDriveController

joint_state_broadcaster:
  ros__parameters: {}

diff_drive_controller:
  ros__parameters:
    left_wheels:
      - left_wheel_front_joint
      - left_wheel_middle_joint
      - left_wheel_rear_joint
    right_wheels:
      - right_wheel_front_joint
      - right_wheel_middle_joint
      - right_wheel_rear_joint
    wheel_separation: 0.5
    wheel_radius: 0.1
    cmd_vel_timeout: 0.25
    publish_rate: 50
    odom_frame: odom
    base_frame: base_link
    velocity_rolling_window_size: 2
