<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>gui_vibecoded</name>
  <version>0.6.7</version>
  <description>GUI VibeCoded</description>
  <maintainer email="fuckoff@gmail.com">ur mum</maintainer>
  <license>MIT</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>rclcpp</depend>
  <depend>std_msgs</depend>
  <depend>kratos_msgs</depend>

  <depend>gstreamer1.0</depend>
  <depend>gstreamer1.0-plugins-base</depend>
  <depend>gstreamer1.0-plugins-good</depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
